export {
  REWRITE_PATCH_SYSTEM,
  REWRITE_SYSTEM,
  buildPatchRewriteMessages,
  buildRewriteMessages,
  parsePatchResponse,
  parseRewriteResponse,
  rewriteSystemPrompt,
  shortHypothesis,
  stripFences,
} from "./rewrite.js";
export type { PatchProposal, RewriteOptions, RewriteResult } from "./rewrite.js";
export {
  DEFAULT_PATCH_CHAR_THRESHOLD,
  DEFAULT_R0_MAX_PATCH_RATIO,
  DEFAULT_R1_MAX_PATCH_RATIO,
  PatchError,
  applyEdits,
  applyPromptPatch,
  applyUnifiedDiff,
  assertSafePatch,
  changedCharRatio,
  contentHash,
  dryRunPatch,
  formatSectionMap,
  looksLikeUnifiedDiff,
  parseEdits,
  parseMaxPatchRatio,
  parseRewriteMode,
  resolveAllowFullRewrite,
  resolveEffectiveRewriteMode,
  resolveMaxPatchRatio,
  resolvePatchThreshold,
  sectionMapArtifact,
  splitLines,
  splitSections,
} from "./patch.js";
export type {
  ApplyResult,
  EffectiveRewriteMode,
  PatchEdit,
  PatchOp,
  PromptSection,
  RewriteMode,
  SectionMapArtifact,
} from "./patch.js";
export {
  R1_REWRITE_PATCH_SYSTEM,
  R1_REWRITE_SYSTEM,
  buildR1RewriteMessages,
  dedupeProposals,
  dryRunProposals,
  materializeR1Proposals,
  parseR1Candidates,
  parseR1RawCandidates,
  promptKey,
  proposeR1Candidates,
} from "./r1-rewrite.js";
export type { ProposeR1Options, R1Proposal, R1RawCandidate } from "./r1-rewrite.js";
